# Site
title: hexo-tag-mmedia
subtitle: hexo-tag-mmedia demo
description: "A demo for hexo-tag-mmedia"
author: "MonoLogueChi"
language: "zh-Hans"
timezone: "Asia/Shanghai"

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://demo.hexo-tag-mmedia.u2sb.com
root: /
permalink: :title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: "**/**.html"

# Theme
theme: melody

# Writing
highlight:
  enable: true
  line_number: true

mmedia:
  loader_path: https://cdn.jsdelivr.net/npm/hexo-tag-mmedia@1.2.1/mmedia-loader.js
  aplayer:
    default:
      contents:
        autoplay: false
  meting:
    default:
      loop: all
      order: random
  bilibili:
    default:
      page: 1
