config_default:
  assets:
    js: /assets/js/
    css: /assets/css/
  audio:
    default:
  video:
    default:
  aplayer:
    js: 
    css: 
    default:
      contents:
  meting:
    js: 
    api:
    default:
  dplayer:
    js: https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js
    hls_js: https://cdn.jsdelivr.net/npm/hls.j/dist/hls.min.js
    dash_js: https://cdn.jsdelivr.net/npm/dashjs/dist/dash.all.min.js
    shaka_dash_js: https://cdn.jsdelivr.net/npm/shaka-player/dist/shaka-player.compiled.js
    flv_js: https://cdn.jsdelivr.net/npm/flv.js/dist/flv.min.js
    webtorrent_js: https://cdn.jsdelivr.net/npm/webtorrent/webtorrent.min.js
    default:
      contents:
